#定义环境引用的配置文件
server:
  port: 8089
spring:
  profiles:
    active: dev
  application:
    name: spring-cloud-eureka-server

eureka:
  instance:
    #心跳时间间隔
    lease-renewal-interval-in-seconds: 10
    #无心跳多久后,该服务失效
    lease-expiration-duration-in-seconds: 30
    appname: eureka-server
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true

