#定义环境引用的配置文件
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8089/eureka/
    # 间隔多久去拉取服务注册信息
    registry-fetch-interval-seconds: 5

logging:
  path: /data/logs/spring-cloud-config-server


